### PR TITLE
Update dependencies to match v1.16.0

### PR DESCRIPTION
**Pull request by jamesmyatt**
See https://github.com/Trusted-AI/adversarial-robustness-toolbox/blob/1.16.0/setup.py. Also matched the order of the dependencies.

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by jamesmyatt** [comment]
@conda-forge-admin, please rerender

**Comment by jamesmyatt** [comment]
@rluria14 @oblute @ndmaxar @JennaLipscomb @d-cunningham can this be merged, please?

**Comment by jamesmyatt** [comment]
@rluria14 @oblute @ndmaxar @JennaLipscomb @d-cunningham can this be merged, please?

**Comment by lockwoodar** [comment]
@jamesmyatt 

You can close this pull request as it is superseded by #48.  Please follow issue #47 if you still need updates on resolution, as I will work toward assuming maintenance ownership if the members of `mxr-conda` are no longer active.

**Comment by lockwoodar** [comment]
Closing, as #48 resolved this to match current state.

**Comment by lockwoodar** [comment]
Closing as merging #48 resolved dependencies to match current state.

**Pull request closed without merging**
